export const ui = {
  activeCategories: [],
  activeLabels: [],
  activeQuery: '',
  categories: [],
  installed: [],
  isFetching: false,
  isFiltered: false,
  labels: [],
  limit: 50,
  page: 1,
  pages: 1,
  plugins: [],
  query: '',
  showFilter: false,
  showResults: false,
  sort: 'relevance',
  total: 0,
  trend: [],
  updated: [],
  view: 'Tiles'
};
